language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=lint
script: npm run $TEST_SUITE
